module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    "bg-primary",
    "bg-primary_shade_1",
    "bg-primary_shade_2",
    "bg-primary_shade_3",
    "bg-secondary",
    "bg-secondary_shade_1",
    "bg-secondary_shade_2",
    "bg-secondary_shade_3",
    "bg-dark_gray",
    "bg-light-gray",
    "text-primary",
    "text-primary_shade_1",
    "text-primary_shade_2",
    "text-primary_shade_3",
    "text-secondary",
    "text-secondary_shade_1",
    "text-secondary_shade_2",
    "text-secondary_shade_3",
    "text-dark_gray",
    "bg-light_gray",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        primary_shade_1: "var(--color-primary_shade_1)",
        primary_shade_2: "var(--color-primary_shade_2)",
        primary_shade_3: "var(--color-primary_shade_3)",
        secondary: "var(--color-secondary)",
        secondary_shade_1: "var(--color-secondary_shade_1)",
        secondary_shade_2: "var(--color-secondary_shade_2)",
        secondary_shade_3: "var(--color-secondary_shade_3)",
        dark_gray: "var(--color-dark_gray)",
        light_gray: "var(--color-light_gray)",
        editor_dark_purple: "#4945FF",
        editor_medium_purple: "#928fff",
        editor_light_purple: "#dbdaff",

      },
    },
  },
  plugins: [],
};
