module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    "bg-primary",
    "bg-secondary",
    "bg-darkGray",
    "bg-mediumGray",
    "bg-lightGray",
    "bg-actionBlue",
    "bg-successLight",
    "bg-successDark",
    "bg-errorLight",
    "bg-errorDark",
    "text-primary",
    "text-secondary",
    "text-darkGray",
    "text-mediumGray",
    "text-lightGray",
    "text-actionBlue",
    "text-successLight",
    "text-successDark",
    "text-errorLight",
    "text-errorDark",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        darkGray: "#333333",
        mediumGray: "#797B7A",
        lightGray: "#D3D3D3",
        actionBlue: "#2F77EE",
        successLight: "#86CCA4",
        successDark: "#0E4325",
        errorLight: "#FCBABA",
        errorDark: "#5B0000",
        editorDarkPurple: "#4945FF",
        editorMediumPurple: "#928fff",
        editorLightPurple: "#dbdaff",

      },
    },
  },
  plugins: [],
};
